import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar/NavBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html  lang="en">
      <body className={`${inter.className} md:px-32 px-10 py-10`}>
      <NavBar/>
        {children}</body>
      {/* <div className="w-full h-20 flex justify-center text-white bg-gray-800 items-center p-0">© 2023<span className="text-[#FD6F00] font-bold px-2"> Mumair</span> All Rights Reserved , Inc.</div> */}
    </html>
  );
}
